=== MrManfredi/ImageHandler/src/main/resources/tagsMap.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://map.tags.manfredi.kpi"
           xmlns:tns="http://map.tags.manfredi.kpi"
           elementFormDefault="qualified">
    <xs:complexType name="Tag">
        <xs:sequence>
            <xs:element name="alias" minOccurs="1" maxOccurs="unbounded">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[a-zA-Z_\d()]+"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="name" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="#[a-zA-Z_\d]+"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="priority" type="xs:byte" default="50"/>
    </xs:complexType>

    <xs:element name="tagsMap">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="tag" type="tns:Tag" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== MrManfredi/ImageHandler/src/main/resources/tagsMapExample.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<tns:tagsMap xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://map.tags.manfredi.kpi"
         xsi:schemaLocation="http://map.tags.manfredi.kpi tagsMap.xsd"
         xmlns:tns="http://map.tags.manfredi.kpi">

    <tns:tag name="#animal">
        <tns:alias>cat</tns:alias>
        <tns:alias>dog</tns:alias>
        <tns:alias>bird</tns:alias>
    </tns:tag>

    <tns:tag name="#weapon">
        <tns:alias>sword</tns:alias>
        <tns:alias>gun</tns:alias>
    </tns:tag>

    <tns:tag name="#food">
        <tns:alias>orange</tns:alias>
        <tns:alias>cookie</tns:alias>
        <tns:alias>meat</tns:alias>
    </tns:tag>

</tns:tagsMap>
